# Generated by Selenium IDE
import pytest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

class TestLogin:
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.driver.maximize_window()  # Maximize window to prevent hidden elements
        self.wait = WebDriverWait(self.driver, 10)  # Explicit wait

    def teardown_method(self, method):
        self.driver.quit()

    def test_login(self):
        self.driver.get("http://localhost/coffeeduplicate/index.php")

        # Wait for login button and click it
        login_button = self.wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, ".nav-item:nth-child(6) span:nth-child(2)")))
        login_button.click()

        # Wait for email field to appear and enter email
        email_field = self.wait.until(EC.visibility_of_element_located((By.NAME, "email")))
        email_field.send_keys("serenitystyles.online@gmail.com")

        # Wait for password field to appear and enter password
        password_field = self.wait.until(EC.visibility_of_element_located((By.NAME, "password")))
        password_field.send_keys("Serenity@123")

        # Click login button
        login_btn = self.wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, ".btn")))
        login_btn.click()

        # Optional: Wait to confirm login success (Replace with actual success element)
        time.sleep(3)

